name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/New_York
          base_indepth: yes
          config_display: columns
          config_padding: 8 + 8%, 20 + 21%

          plugin_achievements: yes
          plugin_activity: yes
          plugin_calendar: yes
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stars: yes
          plugin_traffic: yes

          plugin_languages: yes
          plugin_languages_ignored: >-
            dockerfile, makefile, shell, markdown, json, html, css
          plugin_languages_indepth: yes
          commits_authoring: 103906421+ahmadk953@users.noreply.github.com
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 5
          plugin_languages_analysis_timeout: 15

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_languages_ignored: >-
            dockerfile, makefile, shell, markdown, json, html, css

          plugin_code: yes
          plugin_code_languages: javascript, typescript, java, tsx
